services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\TaskManager\:
        resource: ../src/*
        exclude:
            - ../src/Exception/*
            - ../src/TaskManagerBundle.php
