services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\TaskManager\:
        resource: ../src/*
        exclude:
            - ../src/Exception/*
            - ../src/Task/*
            - ../src/TaskManagerBundle.php

    Torr\TaskManager\Manager\TaskManager:
        $receivers: '@messenger.receiver_locator'
