services:
    _defaults:
        autoconfigure: true
        autowire: true

    Torr\TaskManager\:
        resource: ../src/*
        exclude:
            - ../src/Entity/*
            - ../src/Event/*
            - ../src/Exception/*
            - ../src/Task/*
            - ../src/TaskManagerBundle.php

    Torr\TaskManager\Transport\TransportsHelper:
        $transports: '@messenger.receiver_locator'
